-- Tabla principal: CLIENTES
CREATE TABLE CLIENTES (
    ID_CLIENTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE
);

-- Tabla secundaria: PEDIDOS
CREATE TABLE PEDIDOS (
    ID_PEDIDO NUMBER PRIMARY KEY,
    FECHA DATE NOT NULL,
    TOTAL NUMBER(10, 2),
    ID_CLIENTE NUMBER,
    
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE)
    REFERENCES CLIENTES(ID_CLIENTE)
    ON DELETE CASCADE
);

-- Insertar en CLIENTES
INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, EMAIL) VALUES (1, 'Juan Pérez', 'juan.perez@mail.com');
INSERT INTO CLIENTES (ID_CLIENTE, NOMBRE, EMAIL) VALUES (2, 'Ana López', 'ana.lopez@mail.com');

-- Insertar en PEDIDOS
INSERT INTO PEDIDOS (ID_PEDIDO, FECHA, TOTAL, ID_CLIENTE) VALUES (101, SYSDATE, 500.00, 1);
INSERT INTO PEDIDOS (ID_PEDIDO, FECHA, TOTAL, ID_CLIENTE) VALUES (102, SYSDATE, 300.00, 1);
INSERT INTO PEDIDOS (ID_PEDIDO, FECHA, TOTAL, ID_CLIENTE) VALUES (201, SYSDATE, 700.00, 2);

