SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;

-- HACER QUE HAYA EMPLEADOS QUE NO ESTÉN EN NINGÚN DEPTO
UPDATE EMPLEADOS 
SET DEPARTAMENTO_ID = null
where departamento_id = 40;

-- INNER JOIN
SELECT NOMBRE_COMPLETO AS EMPLEADO, NOMBRE AS DEPARTAMENTO 
FROM EMPLEADOS E INNER JOIN DEPARTAMENTOS D ON (E.DEPARTAMENTO_ID = D.DEPARTAMENTO_ID);

-- FULL JOIN
SELECT NOMBRE_COMPLETO AS EMPLEADO, NOMBRE AS DEPARTAMENTO 
FROM EMPLEADOS E FULL JOIN DEPARTAMENTOS D ON (E.DEPARTAMENTO_ID = D.DEPARTAMENTO_ID);

-- LEFT JOIN
SELECT NOMBRE_COMPLETO AS EMPLEADO, NOMBRE AS DEPARTAMENTO 
FROM EMPLEADOS E LEFT JOIN DEPARTAMENTOS D ON (E.DEPARTAMENTO_ID = D.DEPARTAMENTO_ID);

-- RIGHT JOIN
SELECT NOMBRE_COMPLETO AS EMPLEADO, NOMBRE AS DEPARTAMENTO 
FROM EMPLEADOS E RIGHT JOIN DEPARTAMENTOS D ON (E.DEPARTAMENTO_ID = D.DEPARTAMENTO_ID)