-- Este es un comentario

SELECT *
FROM DEPARTAMENTOS;

SELECT *
FROM EMPLEADOS;

-- EMPLEADOS CON SALARIO CON SALARIO SUPERIOR 3000
SELECT 
    NOMBRE AS NOMBRE_COMPLETO, 
    SALARIO AS SUELDO
FROM EMPLEADOS
WHERE SALARIO > 3000

-- EMPLEADOS QUE PERTENEZCAN AL DEPARTAMENTO DE TI
SELECT NOMBRE,
       DEPARTAMENTO_ID
FROM EMPLEADOS
WHERE DEPARTAMENTO_ID = 30

-- Empleados con un salario superior a 3000 en el departamento de TI
SELECT NOMBRE,
       DEPARTAMENTO_ID,
       SALARIO
FROM EMPLEADOS
WHERE (DEPARTAMENTO_ID = 30) AND (SALARIO > 3000)

-- Empleados cuyo nombre comience con C
SELECT NOMBRE
FROM EMPLEADOS
WHERE NOMBRE LIKE 'C%' 

-- Empleados que estén en el departamento de Finanzas y también los que estén TI
SELECT NOMBRE,
       DEPARTAMENTO_ID
FROM EMPLEADOS
WHERE (DEPARTAMENTO_ID = 20) OR (DEPARTAMENTO_ID = 30) 

SELECT NOMBRE,
       DEPARTAMENTO_ID
FROM EMPLEADOS
WHERE DEPARTAMENTO_ID IN (20, 30) 