SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;

-- AGRUPAMIENTO DE EMPLEADOS POR DEPARTAMENTO
SELECT DEPARTAMENTO_ID AS DEPARTAMENTO, COUNT(*) AS CANTIDAD_EMPLEADOS
FROM EMPLEADOS
GROUP BY DEPARTAMENTO_ID;

-- GRUPOS EN LOS QUE HAYA MÁS DE UN EMPLEADO EN ORDEN DESCENTE POR DEPARTAMENTO_ID
SELECT DEPARTAMENTO_ID AS DEPARTAMENTO, COUNT(*) AS CANTIDAD_EMPLEADOS
FROM EMPLEADOS
GROUP BY DEPARTAMENTO_ID
HAVING COUNT(*) > 1
ORDER BY DEPARTAMENTO_ID;

-- AGRUPAMIENTO DE EMPLEADOS POR DEPARTAMENTO; SUMA DE LOS SALARIOS DE TODOS EMPLEADOS EN CADA GRUPO, FILTRAMOS POR GRUPOS EN QUE GANEN MÁS DE 5000
SELECT DEPARTAMENTO_ID AS DEPARTAMENTO, COUNT(*) AS CANTIDAD_EMPLEADOS, SUM(SALARIO) AS SALARIO_TOTAL
FROM EMPLEADOS
GROUP BY DEPARTAMENTO_ID
HAVING SUM(SALARIO) > 5000
ORDER BY DEPARTAMENTO_ID;

-- CONFIRMACIÓN DE TRANSACCIONES 
COMMIT
