SELECT * FROM EMPLEADOS;
SELECT * FROM DEPARTAMENTOS;

-- ASCENDENTE POR UNA COLUMNA
SELECT NOMBRE, EMPLEADO_ID
FROM EMPLEADOS
ORDER BY NOMBRE;

-- DESCENDENTE POR UNA COLUMNA
SELECT NOMBRE, EMPLEADO_ID
FROM EMPLEADOS
ORDER BY NOMBRE DESC;

-- ORDENAR POR VARIAS COLUMNAS 
SELECT NOMBRE, DEPARTAMENTO_ID, SALARIO
FROM EMPLEADOS
ORDER BY DEPARTAMENTO_ID DESC, SALARIO;

-- TABLA PARA HACER PRUEBAS 
SELECT SYSDATE AS FECHA_ACTUAL FROM DUAL; -- OBTENER LA FECHA DEL SISTEMA
SELECT 3+4 AS SUMA FROM DUAL; -- OBTENER EL RESULTADO DE LA SUMA 3+4

-- ORDENAR LOS EMPLEADOS EN BASE A SU SALARIO ANUAL
SELECT NOMBRE, SALARIO * 12 AS SALARIO_ANUAL
FROM EMPLEADOS
ORDER BY SALARIO_ANUAL;

SELECT NOMBRE, SALARIO * 12
FROM EMPLEADOS
ORDER BY (SALARIO * 12);

-- ORDENAR POR POSICIÓN DE LA COLUMNA
SELECT NOMBRE, SALARIO, FECHA_CONTRATACION
FROM EMPLEADOS
ORDER BY FECHA_CONTRATACION;

SELECT NOMBRE, SALARIO, FECHA_CONTRATACION
FROM EMPLEADOS
ORDER BY 3;

-- NULLS FIRST & NULLS LAST
SELECT NOMBRE, SALARIO, FECHA_CONTRATACION
FROM EMPLEADOS
ORDER BY FECHA_CONTRATACION NULLS FIRST;

SELECT NOMBRE, SALARIO, FECHA_CONTRATACION
FROM EMPLEADOS
ORDER BY FECHA_CONTRATACION NULLS LAST;